;Open the Clipboard GUI
Alt & `:: MoreClipboardsOpenGUI()

;Copy to Clipboards (Ctrl + Number)
^1:: MoreClipboardsCopy(1)
^2:: MoreClipboardsCopy(2)
^3:: MoreClipboardsCopy(3)
^4:: MoreClipboardsCopy(4)
^5:: MoreClipboardsCopy(5)
^6:: MoreClipboardsCopy(6)
^7:: MoreClipboardsCopy(7)
^8:: MoreClipboardsCopy(8)
^9:: MoreClipboardsCopy(9)
^0:: MoreClipboardsCopy(10)

;Paste from Clipboards (Alt + Number)
!1:: MoreClipboardsPaste(1)
!2:: MoreClipboardsPaste(2)
!3:: MoreClipboardsPaste(3)
!4:: MoreClipboardsPaste(4)
!5:: MoreClipboardsPaste(5)
!6:: MoreClipboardsPaste(6)
!7:: MoreClipboardsPaste(7)
!8:: MoreClipboardsPaste(8)
!9:: MoreClipboardsPaste(9)
!0:: MoreClipboardsPaste(10)