+^!F1::Send {Raw}{F1}
+^!F2::Send {Raw}{F2}
+^!F3::Send {Raw}{F3}
+^!F4::Send {Raw}{F4}
+^!F5::Send {Raw}{F5}
+^!F6::Send {Raw}{F6}
+^!F7::Send {Raw}{F7}
+^!F8::Send {Raw}{F8}
+^!F9::Send {Raw}{F9}
+^!F10::Send {Raw}{F10}
+^!F11::Send {Raw}{F11}
+^!F12::Send {Raw}{F12}
+^!Space::Send {Raw}{Space}
+^!Tab::Send {Raw}{Tab}
+^!Enter::Send {Raw}{Enter}
+^!Escape::Send {Raw}{Escape}
+^!Backspace::Send {Raw}{Backspace}
+^!Delete::Send {Raw}{Delete}
+^!Insert::Send {Raw}{Insert}
+^!Home::Send {Raw}{Home}
+^!End::Send {Raw}{End}
+^!PgUp::Send {Raw}{PgUp}
+^!PgDn::Send {Raw}{PgDn}
+^!Up::Send {Raw}{Up}
+^!Down::Send {Raw}{Down}
+^!Left::Send {Raw}{Left}
+^!Right::Send {Raw}{Right}
+^!ScrollLock::Send {Raw}{ScrollLock}
+^!CapsLock::Send {Raw}{CapsLock}
+^!NumLock::Send {Raw}{NumLock}
+^!Numpad0::Send {Raw}{Numpad0}
+^!Numpad1::Send {Raw}{Numpad1}
+^!Numpad2::Send {Raw}{Numpad2}
+^!Numpad3::Send {Raw}{Numpad3}
+^!Numpad4::Send {Raw}{Numpad4}
+^!Numpad5::Send {Raw}{Numpad5}
+^!Numpad6::Send {Raw}{Numpad6}
+^!Numpad7::Send {Raw}{Numpad7}
+^!Numpad8::Send {Raw}{Numpad8}
+^!Numpad9::Send {Raw}{Numpad9}
+^!NumpadDot::Send {Raw}{NumpadDot}
+^!NumpadDiv::Send {Raw}{NumpadDiv}
+^!NumpadMult::Send {Raw}{NumpadMult}
+^!NumpadAdd::Send {Raw}{NumpadAdd}
+^!NumpadSub::Send {Raw}{NumpadSub}
+^!NumpadEnter::Send {Raw}{NumpadEnter}
+^!NumpadIns::Send {Raw}{NumpadIns}
+^!NumpadEnd::Send {Raw}{NumpadEnd}
+^!NumpadDown::Send {Raw}{NumpadDown}
+^!NumpadPgDn::Send {Raw}{NumpadPgDn}
+^!NumpadLeft::Send {Raw}{NumpadLeft}
+^!NumpadClear::Send {Raw}{NumpadClear}
+^!NumpadRight::Send {Raw}{NumpadRight}
+^!NumpadHome::Send {Raw}{NumpadHome}
+^!NumpadUp::Send {Raw}{NumpadUp}
+^!NumpadPgUp::Send {Raw}{NumpadPgUp}
+^!NumpadDel::Send {Raw}{NumpadDel}
+^!PrintScreen::Send {Raw}{PrintScreen}
+^!CtrlBreak::Send {Raw}{CtrlBreak}
+^!Pause::Send {Raw}{Pause}
LControl & RControl Up::Send {Raw}{Control}
LAlt & RAlt Up::Send {Raw}{Alt}
LShift & RShift Up::Send {Raw}{Shift}